name: Databricks CI
on: [push, pull_request]
jobs: 
  run-databricks-ci: 
    environment: databricks-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -V
      - run: pip install virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt
      - name: Install Databricks CLI
        run: pip install databricks-cli
      - name: Configure Databricks CLI
        run: |
          databricks configure --token --profile DEFAULT <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF
      - name: Get Root Directories of Modified Files
        shell: bash
        run: |
          git fetch origin main:main
          git diff main --name-only --diff-filter=d | sed 's|/.*||' | sort -u > MODIFIED_DIRS
          echo "GITHUB_MODIFIED_DIRS=$(cat MODIFIED_DIRS)" >> $GITHUB_ENV
          echo ${{ env.GITHUB_MODIFIED_DIRS}}
      - run: pytest --junitxml=unit-testresults.xml ${{ env.GITHUB_MODIFIED_DIRS}}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: unit-testresults.xml