name: Databricks CI
on: [pull_request]
jobs: 
  run-databricks-ci: 
    environment: databricks-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -V
      - run: pip install virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt
      - name: Install Databricks CLI
        run: pip install databricks-cli
      - name: Configure Databricks CLI
        run: |
          echo "y
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          ${{ secrets.DATABRICKS_CLUSTER_ID }}" | databricks configure --token --profile DEFAULT
      # - name: Get Root Directories of Modified Files
      #   shell: bash
      #   run: |
      #     git fetch origin main:main
      #     git diff main --name-only --diff-filter=d | grep -v '^\.github/' | sed 's|/.*||' | sort -u | sed 's|$|/test|' | tr '\n' ' ' > MODIFIED_DIRS
      #     MODIFIED_DIRS_CONTENT=$(cat MODIFIED_DIRS)
      #     echo "GITHUB_MODIFIED_DIRS=$MODIFIED_DIRS_CONTENT" >> $GITHUB_ENV
      # - run: echo $GITHUB_MODIFIED_DIRS
      - run: pytest --junitxml=unit-testresults.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: unit-testresults.xml